set_property IOSTANDARD LVCMOS33 [get_ports {M[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {M[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QUO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QUO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QUO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {QUO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {REM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {REM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {REM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {REM[0]}]


set_property PACKAGE_PIN V10 [get_ports {Q[3]}]
set_property PACKAGE_PIN U11 [get_ports {Q[2]}]
set_property PACKAGE_PIN U12 [get_ports {Q[1]}]
set_property PACKAGE_PIN H6 [get_ports {Q[0]}]

set_property PACKAGE_PIN T13 [get_ports {M[3]}]
set_property PACKAGE_PIN R16 [get_ports {M[2]}]
set_property PACKAGE_PIN U8 [get_ports {M[1]}]
set_property PACKAGE_PIN T8 [get_ports {M[0]}]

set_property PACKAGE_PIN V11 [get_ports {QUO[3]}]
set_property PACKAGE_PIN V12 [get_ports {QUO[2]}]
set_property PACKAGE_PIN V14 [get_ports {QUO[1]}]
set_property PACKAGE_PIN V15 [get_ports {QUO[0]}]

set_property PACKAGE_PIN T16 [get_ports {REM[3]}]
set_property PACKAGE_PIN U14 [get_ports {REM[2]}]
set_property PACKAGE_PIN T15 [get_ports {REM[1]}]
set_property PACKAGE_PIN V16 [get_ports {REM[0]}]
